services:
  api:
    build: .
    container_name: inovate-barber-api
    ports:
      - "8082:8082"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/inovate_barber_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_FLYWAY_ENABLED: "true"
      SECURITY.JWT.SECRET: 2853570d-1f5b-4b34-9670-fe5b1ff0b29b
      SECURITY.JWT.EXPIRATION: 86400000

  postgres:
    image: postgres:16
    container_name: postgres_inovate_db
    environment:
      POSTGRES_DB: inovate_barber_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: